# coding: utf-8

# flake8: noqa

"""
    Weft Event Ingestion API

    The Weft Event Ingestion API is a RESTful API that allows you to submit events for processing and storage. The API is designed to be used by Weft customers and partners to submit events from their own applications and systems. The API is also used by Weft's own backend infrastructure to ingest events from various sources.  The API is secured using the Bearer Authentication scheme with JWT tokens. To obtain a JWT token, please contact Weft at team@goweft.com   # noqa: E501

    The version of the OpenAPI document: 2.3.1
    Contact: team@goweft.com
    Generated by: https://openapi-generator.tech
"""

__version__ = "1.0.0"

# import ApiClient
from openapi_client.api_client import ApiClient

# import Configuration
from openapi_client.configuration import Configuration

# import exceptions
from openapi_client.exceptions import OpenApiException
from openapi_client.exceptions import ApiAttributeError
from openapi_client.exceptions import ApiTypeError
from openapi_client.exceptions import ApiValueError
from openapi_client.exceptions import ApiKeyError
from openapi_client.exceptions import ApiException
