# coding: utf-8

"""
    Weft Event Ingestion API

    The Weft Event Ingestion API is a RESTful API that allows you to submit events for processing and storage. The API is designed to be used by Weft customers and partners to submit events from their own applications and systems. The API is also used by Weft's own backend infrastructure to ingest events from various sources.  The API is secured using the Bearer Authentication scheme with JWT tokens. To obtain a JWT token, please contact Weft at team@goweft.com   # noqa: E501

    The version of the OpenAPI document: 2.3.1
    Contact: team@goweft.com
    Generated by: https://openapi-generator.tech
"""

from setuptools import setup, find_packages  # noqa: H301

NAME = "weft-client"
VERSION = "1.2.4"
# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools

REQUIRES = [
    "certifi >= 14.5.14",
    "frozendict ~= 2.3.4",
    "python-dateutil ~= 2.7.0",
    "setuptools >= 21.0.0",
    "typing_extensions ~= 4.3.0",
    "urllib3 ~= 1.26.7",
]

setup(
    name=NAME,
    version=VERSION,
    description="Weft Event Ingestion API",
    author="Weft Finance, Inc",
    author_email="team@goweft.com",
    url="",
    keywords=["OpenAPI", "OpenAPI-Generator", "Weft Event Ingestion API"],
    python_requires=">=3.7",
    install_requires=REQUIRES,
    package_dir={"": "src"},
    packages=find_packages(where="src", exclude=["test", "tests"]),
    include_package_data=True,
    py_modules=["weft_client"],
    long_description="""\
    The Weft Event Ingestion API is a RESTful API that allows you to submit events for processing and storage. The API is designed to be used by Weft customers and partners to submit events from their own applications and systems. The API is also used by Weft&#x27;s own backend infrastructure to ingest events from various sources.  The API is secured using the Bearer Authentication scheme with JWT tokens. To obtain a JWT token, please contact Weft at team@goweft.com   # noqa: E501
    """
)
