# coding: utf-8

"""
    Weft Events Api

    The Weft Event Ingestion API is a RESTful API that allows you to submit events for processing and storage. The API is secured using the Bearer Authentication scheme with JWT tokens. To obtain a JWT token, please contact Weft at team@goweft.com 

    The version of the OpenAPI document: 2.3.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.event_input import EventInput  # noqa: E501

class TestEventInput(unittest.TestCase):
    """EventInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EventInput:
        """Test EventInput
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EventInput`
        """
        model = EventInput()  # noqa: E501
        if include_optional:
            return EventInput(
                name = 'api_call',
                timestamp = '2023-09-13T18:25:43.511Z',
                customer_alias = 'customer_12345',
                data = {"key1":"processing_duration","key2":"api_url"},
                ref = '4f6cf35x-2c4y-483z-a0a9-158621f77a21'
            )
        else:
            return EventInput(
                name = 'api_call',
                timestamp = '2023-09-13T18:25:43.511Z',
                customer_alias = 'customer_12345',
        )
        """

    def testEventInput(self):
        """Test EventInput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
