# coding: utf-8

"""
    Weft Event Ingestion API

    The Weft Event Ingestion API is a RESTful API that allows you to submit events for processing and storage. The API is designed to be used by Weft customers and partners to submit events from their own applications and systems. The API is also used by Weft's own backend infrastructure to ingest events from various sources.  The API is secured using the Bearer Authentication scheme with JWT tokens. To obtain a JWT token, please contact Weft at team@goweft.com   # noqa: E501

    The version of the OpenAPI document: 2.3.1
    Contact: team@goweft.com
    Generated by: https://openapi-generator.tech
"""

from openapi_client.paths.refresh_token.post import RefreshUser
from openapi_client.paths.events.put import SendEvents


class EventsApi(
    RefreshUser,
    SendEvents,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
